# Generated by Django 2.2.7 on 2020-02-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('numero_viaje', models.CharField(default='00000000', max_length=1024)),
                ('transportista', models.CharField(max_length=50)),
                ('site_destino_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('tipo_viaje', models.CharField(default='sin espesificar', max_length=30)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('id_pasajero', models.CharField(max_length=50)),
                ('nombre_pasajero', models.CharField(max_length=50)),
                ('apellido_pasajero', models.CharField(max_length=50)),
                ('campaña_pasajero', models.CharField(max_length=50)),
                ('site_pasajero', models.CharField(max_length=50)),
                ('ruta_pasajero', models.CharField(max_length=50)),
                ('direccion_pasajero', models.CharField(max_length=150)),
                ('excepcion', models.BooleanField(default=False)),
                ('razon_excepcion', models.TextField(default='Sin espesificar')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeAdministrativo',
            fields=[
                ('numero_viaje', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('origen', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('tipo_visita', models.CharField(max_length=30)),
                ('numero_contacto', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('vendor', models.ForeignKey(default='Sin espesificar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
            ],
        ),
    ]
