# Generated by Django 3.2 on 2022-06-08 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruta', '0002_tipo_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excepciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_excepcion', models.CharField(max_length=50)),
                ('detalle_excepcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ViajeAdministrativo',
            fields=[
                ('numero_viaje', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('origen', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('tipo_visita', models.CharField(max_length=30)),
                ('numero_contacto', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('vendor', models.ForeignKey(default='Sin espesificar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('numero_viaje', models.CharField(default='00000000', max_length=1024)),
                ('site_destino_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('tipo_viaje', models.CharField(default='sin espesificar', max_length=30)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('id_pasajero', models.CharField(max_length=50)),
                ('nombre_pasajero', models.CharField(max_length=50)),
                ('apellido_pasajero', models.CharField(max_length=50)),
                ('campaña_pasajero', models.CharField(max_length=50)),
                ('site_pasajero', models.CharField(max_length=50)),
                ('direccion_pasajero', models.CharField(max_length=100)),
                ('excepcion', models.BooleanField(default=False)),
                ('razon_excepcion', models.TextField(default='Sin espesificar')),
                ('ruta_pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruta.ruta')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
