# Generated by Django 3.2 on 2022-06-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='id_pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajero.pasajero'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='site_pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajero.cuenta'),
        ),
    ]
