# Generated by Django 2.2.7 on 2020-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='direccion_pasajero',
            field=models.CharField(max_length=100),
        ),
    ]
