# Generated by Django 2.2.7 on 2019-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajeadministrativo',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='viajeadministrativo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
