# Generated by Django 3.2 on 2022-06-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('viajes', '0002_auto_20220618_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='site_pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
