# Generated by Django 2.2.7 on 2019-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20191209_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='site_destino_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
