# Generated by Django 3.2 on 2022-06-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0001_initial'),
        ('viajes', '0003_alter_viaje_site_pasajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='campaña_pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajero.cuenta'),
        ),
    ]
