# Generated by Django 2.2.7 on 2020-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20200102_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='direccion_pasajero',
            field=models.CharField(max_length=150),
        ),
    ]
