# Generated by Django 2.2.7 on 2020-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectorQr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_codigo', models.CharField(max_length=50)),
            ],
        ),
    ]
