# Generated by Django 3.0 on 2022-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id_site', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_site', models.CharField(max_length=50)),
            ],
        ),
    ]
