# Generated by Django 2.2.7 on 2019-12-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
