# Generated by Django 2.2.7 on 2019-12-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='codigo_transportista',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='vendor',
        ),
        migrations.AddField(
            model_name='transportista',
            name='vendor',
            field=models.ManyToManyField(to='vendor.Vendor'),
        ),
    ]
