# Generated by Django 2.2.7 on 2019-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='codigo_transportista',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
