# Generated by Django 2.2.7 on 2019-12-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='codigo_transportista',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
