# Generated by Django 2.2.7 on 2019-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('transportista', '0003_auto_20191207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='codigo_transportista',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='vendor',
        ),
        migrations.AddField(
            model_name='transportista',
            name='vendor',
            field=models.ManyToManyField(to='vendor.Vendor'),
        ),
    ]
