# Generated by Django 3.2 on 2022-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=50)),
                ('tipo_ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_ruta', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
