# Generated by Django 3.0 on 2022-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=50)),
                ('precio_ruta', models.IntegerField(blank=True, null=True)),
                ('tipo_ruta', models.ManyToManyField(blank=True, null=True, to='ruta.Tipo_ruta')),
            ],
        ),
    ]
