# Generated by Django 3.2 on 2022-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
