# Generated by Django 3.2 on 2022-06-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0003_alter_ruta_tipo_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='tipo_ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_ruta',
            field=models.ManyToManyField(blank=True, null=True, to='ruta.Tipo_ruta'),
        ),
    ]
