# Generated by Django 3.2 on 2022-06-08 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__first__'),
        ('ruta', '0002_tipo_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=50, null=True, unique=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('Ruta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ruta.ruta')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajero.cuenta')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=30, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajero.pasajero')),
            ],
        ),
    ]
