# Generated by Django 2.2.7 on 2019-12-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0002_auto_20191218_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='Ruta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ruta.Ruta'),
        ),
    ]
